[build]
  # This assumes your static frontend files are in the 'frontend' directory.
  # If your project had a build step (e.g., for React, Vue, Angular),
  # you would also specify a 'command' here.
  publish = "frontend"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
